/**
 * Dashbook — Figma Code Connect templates (canonical 10)
 * =======================================================
 *
 * Maps the canonical-10 Figma component sets in the Dashbook library file
 * (fileKey 91csAF1OGUmCZROdZlCRSv) to their `@dashfi/svelte` code, so Figma
 * Dev Mode shows the real import + props instead of autogenerated CSS.
 *
 * STATUS / GATE — not yet publishable:
 *   - Code Connect requires a Figma **Organization or Enterprise** plan.
 *     The dashfi team is currently on **Professional**, so `figma connect
 *     publish` will not work until the plan is upgraded.
 *   - The component sets must also be **published to a team library** first
 *     (a Figma-UI action; the Plugin API cannot publish).
 *   - Final home: these belong next to the component source in
 *     `core/libs/svelte-components/lib/` once the lib is published. They live
 *     here as authored templates that travel with the handoff.
 *
 * Prop mappings below are derived from FIGMA_HANDOFF.md §5 and the component
 * APIs in `@dashfi/svelte`. Verify the `@figma/code-connect` import specifier
 * and the Svelte example syntax against the installed CLI version before
 * publishing (Svelte support shape has shifted across releases).
 */
import figma, { html } from '@figma/code-connect/html'

const FILE = 'https://www.figma.com/design/91csAF1OGUmCZROdZlCRSv/Dashbook'

/* Button — node 24:44 — props: Variant, State */
figma.connect(`${FILE}?node-id=24-44`, {
  props: {
    variant: figma.enum('Variant', {
      default: 'default',
      brand: 'brand',
      destructive: 'destructive',
      secondary: 'secondary',
      outline: 'outline',
      ghost: 'ghost',
      link: 'link',
    }),
    disabled: figma.enum('State', { disabled: true }),
  },
  imports: ["import { Button } from '@dashfi/svelte/ui/button'"],
  example: ({ variant, disabled }) =>
    html`<Button variant=${variant} disabled=${disabled}>Button</Button>`,
})

/* Badge — node 25:10 — props: Variant */
figma.connect(`${FILE}?node-id=25-10`, {
  props: {
    variant: figma.enum('Variant', {
      default: 'default',
      secondary: 'secondary',
      destructive: 'destructive',
      outline: 'outline',
    }),
  },
  imports: ["import { Badge } from '@dashfi/svelte/ui/badge'"],
  example: ({ variant }) => html`<Badge variant=${variant}>Badge</Badge>`,
})

/* Input — node 25:24 — props: State (disabled / aria-invalid) */
figma.connect(`${FILE}?node-id=25-24`, {
  props: {
    disabled: figma.enum('State', { disabled: true }),
    invalid: figma.enum('State', { error: true }),
  },
  imports: ["import { Input } from '@dashfi/svelte/ui/input'"],
  example: ({ disabled, invalid }) =>
    html`<Input placeholder="Placeholder" disabled=${disabled} aria-invalid=${invalid} />`,
})

/* Switch — node 26:18 — props: State, Focus */
figma.connect(`${FILE}?node-id=26-18`, {
  props: {
    checked: figma.enum('State', { on: true, 'disabled-on': true, off: false, 'disabled-off': false }),
    disabled: figma.enum('State', { 'disabled-on': true, 'disabled-off': true }),
  },
  imports: ["import { Switch } from '@dashfi/svelte/ui/switch'"],
  example: ({ checked, disabled }) => html`<Switch checked=${checked} disabled=${disabled} />`,
})

/* Checkbox — node 26:34 — props: State, Focus */
figma.connect(`${FILE}?node-id=26-34`, {
  props: {
    checked: figma.enum('State', { checked: true, indeterminate: 'indeterminate', unchecked: false }),
    disabled: figma.enum('State', { disabled: true }),
  },
  imports: ["import { Checkbox } from '@dashfi/svelte/ui/checkbox'"],
  example: ({ checked, disabled }) => html`<Checkbox checked=${checked} disabled=${disabled} />`,
})

/* Alert — node 27:38 — props: Type, Icon */
figma.connect(`${FILE}?node-id=27-38`, {
  props: {
    variant: figma.enum('Type', {
      info: 'info',
      success: 'success',
      warning: 'warning',
      destructive: 'destructive',
    }),
  },
  imports: ["import { Alert, AlertTitle, AlertDescription } from '@dashfi/svelte/ui/alert'"],
  example: ({ variant }) =>
    html`<Alert variant=${variant}>
  <AlertTitle>Title</AlertTitle>
  <AlertDescription>Supporting description text for this alert message.</AlertDescription>
</Alert>`,
})

/* Tabs — node 27:54 (TabsTrigger) — trigger prop: State */
figma.connect(`${FILE}?node-id=27-54`, {
  props: {
    disabled: figma.enum('State', { disabled: true }),
  },
  imports: ["import { Tabs, TabsList, TabsTrigger, TabsContent } from '@dashfi/svelte/ui/tabs'"],
  example: ({ disabled }) => html`<TabsTrigger value="tab" disabled=${disabled}>Tab</TabsTrigger>`,
})

/* Select — node 28:17 (SelectTrigger) — trigger prop: State */
figma.connect(`${FILE}?node-id=28-17`, {
  props: {
    disabled: figma.enum('State', { disabled: true }),
  },
  imports: [
    "import { Select, SelectTrigger, SelectContent, SelectItem } from '@dashfi/svelte/ui/select'",
  ],
  example: ({ disabled }) =>
    html`<SelectTrigger disabled=${disabled}>Selected value</SelectTrigger>`,
})

/* Dialog — node 29:29 (DialogContent) — prop: Size */
figma.connect(`${FILE}?node-id=29-29`, {
  props: {
    size: figma.enum('Size', { sm: 'sm', default: 'default', lg: 'lg' }),
  },
  imports: [
    "import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogFooter } from '@dashfi/svelte/ui/dialog'",
  ],
  example: ({ size }) =>
    html`<DialogContent size=${size}>
  <DialogTitle>Dialog title</DialogTitle>
  <DialogDescription>A short description.</DialogDescription>
  <DialogFooter>
    <Button variant="ghost">Cancel</Button>
    <Button variant="brand">Confirm</Button>
  </DialogFooter>
</DialogContent>`,
})

/* Card — node 29:53 — props: Has header, Has footer (compound composition) */
figma.connect(`${FILE}?node-id=29-53`, {
  props: {
    hasHeader: figma.boolean('Has header'),
    hasFooter: figma.boolean('Has footer'),
  },
  imports: [
    "import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@dashfi/svelte/ui/card'",
  ],
  example: ({ hasHeader, hasFooter }) =>
    html`<Card>
  ${hasHeader
    ? html`<CardHeader><CardTitle>Card title</CardTitle><CardDescription>Card description</CardDescription></CardHeader>`
    : ''}
  <CardContent>Card content sits here.</CardContent>
  ${hasFooter ? html`<CardFooter><Button variant="brand">Action</Button></CardFooter>` : ''}
</Card>`,
})
