// GENERATED by scripts/build-tokens.mjs — paste into the Figma `use_figma` tool to sync the 8 text styles. Idempotent.
const SPECS = [{"name":"Heading / Display","family":"IBM Plex Mono","style":"ExtraLight","size":72,"lh":90,"ls":-1,"tcase":"UPPER"},{"name":"Heading / Page label","family":"IBM Plex Mono","style":"Regular","size":12,"lh":140,"ls":30,"tcase":"UPPER"},{"name":"Heading / Section header","family":"IBM Plex Mono","style":"Medium","size":11,"lh":140,"ls":15,"tcase":"UPPER"},{"name":"Body / Data value","family":"IBM Plex Mono","style":"Regular","size":15,"lh":140,"ls":-2,"tcase":"ORIGINAL"},{"name":"Body / Body lg","family":"Bai Jamjuree","style":"Regular","size":17,"lh":160,"ls":-1,"tcase":"ORIGINAL"},{"name":"Body / Body","family":"Bai Jamjuree","style":"Regular","size":15,"lh":160,"ls":-1,"tcase":"ORIGINAL"},{"name":"Body / Body sm","family":"Bai Jamjuree","style":"Regular","size":13,"lh":150,"ls":-1,"tcase":"ORIGINAL"},{"name":"Body / Caption","family":"Bai Jamjuree","style":"Regular","size":12,"lh":140,"ls":-1,"tcase":"ORIGINAL"}];
const fonts = [...new Map(SPECS.map((s)=>[s.family+'|'+s.style,{family:s.family,style:s.style}])).values()];
for (const f of fonts) await figma.loadFontAsync(f);
const existing = await figma.getLocalTextStylesAsync();
const byName = new Map(existing.map((s)=>[s.name,s]));
let created=0,updated=0,unchanged=0;
for (const spec of SPECS){
	let st = byName.get(spec.name); const isNew=!st;
	if(!st){ st=figma.createTextStyle(); st.name=spec.name; created++; }
	const before = JSON.stringify([st.fontName,st.fontSize,st.lineHeight,st.letterSpacing,st.textCase]);
	st.fontName={family:spec.family,style:spec.style}; st.fontSize=spec.size;
	st.lineHeight={unit:'PERCENT',value:spec.lh}; st.letterSpacing={unit:'PERCENT',value:spec.ls}; st.textCase=spec.tcase;
	st.setSharedPluginData('dsb','runId','ds-figma-20260627');
	if(!isNew){ const after=JSON.stringify([st.fontName,st.fontSize,st.lineHeight,st.letterSpacing,st.textCase]); if(after===before) unchanged++; else updated++; }
}
return { created, updated, unchanged, total: SPECS.length };
