#!/usr/bin/env node
/**
 * Dashbook token build — the single-source-of-truth generator.
 *
 * Reads tokens/dashbook.tokens.json and emits every consumer:
 *   - src/lib/generated/tokens.css   token layer (:root / html.dark / [data-marketing-dark])
 *   - src/lib/generated/theme.css    Tailwind @theme block (--color-*) + dark override
 *   - src/lib/generated/tokens.ts    typed token map (resolved hex) + typography
 *   - tokens/figma.tokens.json       flat colour payload for the Figma variable generator
 *   - tokens/figma-apply.gen.js      ready-to-run use_figma script: syncs Figma variables
 *   - tokens/figma-text-styles.gen.js ready-to-run use_figma script: syncs the 8 text styles
 *   - tokens/lib-tokens.reference.css HSL reference for the @dashfi/svelte lib (packages/brand migration)
 *
 * Run: `pnpm tokens`. Zero dependencies. Refs `{base.<name>}` -> var(--dash-<name>) / Figma alias.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = JSON.parse(readFileSync(join(root, 'tokens/dashbook.tokens.json'), 'utf8'));

const REF = /^\{base\.([a-z0-9-]+)\}$/;
const isRef = (v) => typeof v === 'string' && REF.test(v);
const refName = (v) => v.match(REF)[1];
function entries(group) {
  return Object.entries(group).filter(([k]) => !k.startsWith('$')).map(([name, t]) => ({ name, value: t.$value, type: t.$type }));
}
const base = entries(src.base), product = entries(src.product), mAlias = entries(src['marketing-alias']);
const marketing = entries(src.marketing), scale = entries(src.scale), tw = entries(src.tailwind), twScale = entries(src['tailwind-scale']);
const typo = Object.entries(src.typography).filter(([k]) => !k.startsWith('$')).map(([name, v]) => ({ name, ...v }));

function baseHex(name) { const b = base.find((x) => x.name === name); if (!b) throw new Error(`Unknown base ref: ${name}`); return b.value; }
const css = (v) => (isRef(v) ? `var(--${refName(v)})` : v);
const resolve = (v) => (isRef(v) ? baseHex(refName(v)) : v);
const lightOf = (v) => (typeof v === 'object' ? v.light : v);
const darkOf = (v) => (typeof v === 'object' ? v.dark : v);

/* ---------- tokens.css (token layer) ---------- */
const line = (n, v) => `\t\t--${n}: ${v};`;
const rootLines = [
  '\t\t/* Product semantic — light */', ...product.map((t) => line(t.name, css(lightOf(t.value)))), '',
  '\t\t/* Base palette — brand primitives (single source of every hex) */', ...base.map((t) => line(t.name, t.value)), '',
  '\t\t/* Marketing palette aliases */', ...mAlias.map((t) => line(t.name, css(t.value))), '',
  '\t\t/* Marketing semantic roles — light */', ...marketing.map((t) => line(t.name, css(lightOf(t.value)))), '',
  '\t\t/* Scale — radius, shadows, motion */', ...scale.map((t) => line(t.name, t.value)),
];
const tokensCss = `/* GENERATED by scripts/build-tokens.mjs from tokens/dashbook.tokens.json — do not edit by hand. */
@layer base {
\t:root {
${rootLines.join('\n')}
\t}

\thtml.dark,
\t[data-theme='dark'] {
${product.map((t) => line(t.name, css(darkOf(t.value)))).join('\n')}
\t}

\t[data-marketing-dark] {
${marketing.map((t) => line(t.name, css(darkOf(t.value)))).join('\n')}
\t}
}
`;

/* ---------- theme.css (Tailwind @theme, resolved hex) ---------- */
const themeCss = `/* GENERATED by scripts/build-tokens.mjs from tokens/dashbook.tokens.json — do not edit by hand. */
@theme {
${tw.map((t) => `\t--color-${t.name}: ${resolve(lightOf(t.value))};`).join('\n')}

${twScale.map((t) => `\t--${t.name}: ${t.value};`).join('\n')}
}

@layer base {
\thtml.dark,
\t[data-theme='dark'] {
${tw.map((t) => `\t\t--color-${t.name}: ${resolve(darkOf(t.value))};`).join('\n')}
\t}
}
`;

/* ---------- tokens.ts ---------- */
const tsObj = (arr, mode) => '{\n' + arr.map((t) => `\t\t'${t.name}': ${JSON.stringify(mode ? resolve(mode === 'light' ? lightOf(t.value) : darkOf(t.value)) : t.value)}`).join(',\n') + '\n\t}';
const tokensTs = `// GENERATED by scripts/build-tokens.mjs from tokens/dashbook.tokens.json — do not edit by hand.
export const generatedTokens = {
\tbase: ${tsObj(base)},
\tproduct: { light: ${tsObj(product, 'light')}, dark: ${tsObj(product, 'dark')} },
\tmarketingAlias: ${'{\n' + mAlias.map((t) => `\t\t'${t.name}': ${JSON.stringify(resolve(t.value))}`).join(',\n') + '\n\t}'},
\tmarketing: { light: ${tsObj(marketing, 'light')}, dark: ${tsObj(marketing, 'dark')} },
\tscale: ${tsObj(scale)},
\ttailwind: { light: ${tsObj(tw, 'light')}, dark: ${tsObj(tw, 'dark')} },
\ttypography: ${JSON.stringify(Object.fromEntries(typo.map((t) => [t.name, { family: t.family, style: t.style, size: t.size, lineHeight: t.lineHeight, letterSpacing: t.letterSpacing, case: t.case }])), null, 1).replace(/\n/g, '\n\t')}
} as const;
`;

/* ---------- figma.tokens.json + figma-apply.gen.js ---------- */
const figRef = (v) => (isRef(v) ? { ref: refName(v) } : v);
const figMode = (v) => (typeof v === 'object' && v.light !== undefined ? { light: figRef(v.light), dark: figRef(v.dark) } : figRef(v));
const figma = {
  base: Object.fromEntries(base.map((t) => [t.name, t.value])),
  product: Object.fromEntries(product.map((t) => [t.name, figMode(t.value)])),
  marketingAlias: Object.fromEntries(mAlias.map((t) => [t.name, figMode(t.value)])),
  marketing: Object.fromEntries(marketing.map((t) => [t.name, figMode(t.value)])),
};
const figmaApply = `// GENERATED by scripts/build-tokens.mjs — paste into the Figma \`use_figma\` tool to sync variables
// (collections 3:2 base, 3:3 product Light/Dark, 3:4 marketing Light/Dark). Idempotent.
const T = ${JSON.stringify(figma)};
function pc(s){s=s.trim();if(s.startsWith('rgb')){const n=s.replace(/rgba?\\(|\\)/g,'').split(',').map((x)=>parseFloat(x.trim()));return {r:n[0]/255,g:n[1]/255,b:n[2]/255,a:n[3]==null?1:n[3]};}const h=s.replace('#','');return {r:parseInt(h.slice(0,2),16)/255,g:parseInt(h.slice(2,4),16)/255,b:parseInt(h.slice(4,6),16)/255,a:1};}
const eq=(a,b)=>a&&b&&['r','g','b','a'].every((k)=>Math.abs((a[k]??1)-(b[k]??1))<0.004);
const allVars=await figma.variables.getLocalVariablesAsync();
const C={base:'VariableCollectionId:3:2',product:'VariableCollectionId:3:3',mkt:'VariableCollectionId:3:4'};
const nm=(cid)=>new Map(allVars.filter((v)=>v.variableCollectionId===cid).map((v)=>[v.name,v]));
const baseVars=nm(C.base),prodVars=nm(C.product),mktVars=nm(C.mkt);
const MODE={bd:'3:0',pL:'3:1',pD:'3:2',mL:'3:3',mD:'3:4'};
const figBase=(ref)=>baseVars.get('dash/'+ref.slice(5));
let updated=[],unchanged=0,missing=[];
function ap(v,mode,val){const d=val&&val.ref?{alias:figBase(val.ref)}:{color:pc(val)};const cur=v.valuesByMode[mode];let same;if(d.alias)same=cur&&cur.type==='VARIABLE_ALIAS'&&cur.id===d.alias.id;else same=cur&&typeof cur==='object'&&'r' in cur&&eq(cur,d.color);if(same){unchanged++;return;}v.setValueForMode(mode,d.alias?{type:'VARIABLE_ALIAS',id:d.alias.id}:d.color);updated.push(v.name+'['+mode+']');}
for(const [n,val] of Object.entries(T.base)){const v=baseVars.get('dash/'+n.slice(5));if(!v){missing.push('dash/'+n.slice(5));continue;}ap(v,MODE.bd,val);}
for(const [n,m] of Object.entries(T.product)){const v=prodVars.get(n);if(!v){missing.push(n);continue;}ap(v,MODE.pL,m.light);ap(v,MODE.pD,m.dark);}
for(const [n,val] of Object.entries(T.marketingAlias)){const v=mktVars.get('m/'+n.slice(2));if(!v){missing.push('m/'+n.slice(2));continue;}ap(v,MODE.mL,val);ap(v,MODE.mD,val);}
for(const [n,m] of Object.entries(T.marketing)){const v=mktVars.get('m/'+n.slice(2));if(!v){missing.push('m/'+n.slice(2));continue;}ap(v,MODE.mL,m.light);ap(v,MODE.mD,m.dark);}
return {unchanged,updatedCount:updated.length,updated,missing};
`;

/* ---------- figma-text-styles.gen.js ---------- */
const styleData = typo.map((t) => ({ name: t.name, family: t.family, style: t.style, size: t.size, lh: t.lineHeight, ls: t.letterSpacing, tcase: t.case }));
const figmaText = `// GENERATED by scripts/build-tokens.mjs — paste into the Figma \`use_figma\` tool to sync the 8 text styles. Idempotent.
const SPECS = ${JSON.stringify(styleData)};
const fonts = [...new Map(SPECS.map((s)=>[s.family+'|'+s.style,{family:s.family,style:s.style}])).values()];
for (const f of fonts) await figma.loadFontAsync(f);
const existing = await figma.getLocalTextStylesAsync();
const byName = new Map(existing.map((s)=>[s.name,s]));
let created=0,updated=0,unchanged=0;
for (const spec of SPECS){
\tlet st = byName.get(spec.name); const isNew=!st;
\tif(!st){ st=figma.createTextStyle(); st.name=spec.name; created++; }
\tconst before = JSON.stringify([st.fontName,st.fontSize,st.lineHeight,st.letterSpacing,st.textCase]);
\tst.fontName={family:spec.family,style:spec.style}; st.fontSize=spec.size;
\tst.lineHeight={unit:'PERCENT',value:spec.lh}; st.letterSpacing={unit:'PERCENT',value:spec.ls}; st.textCase=spec.tcase;
\tst.setSharedPluginData('dsb','runId','ds-figma-20260627');
\tif(!isNew){ const after=JSON.stringify([st.fontName,st.fontSize,st.lineHeight,st.letterSpacing,st.textCase]); if(after===before) unchanged++; else updated++; }
}
return { created, updated, unchanged, total: SPECS.length };
`;

/* ---------- lib-tokens.reference.css (HSL, for the packages/brand migration — reference only) ---------- */
function hexToHsl(hex) {
  const h = hex.replace('#', ''); let r = parseInt(h.slice(0, 2), 16) / 255, g = parseInt(h.slice(2, 4), 16) / 255, b = parseInt(h.slice(4, 6), 16) / 255;
  const mx = Math.max(r, g, b), mn = Math.min(r, g, b); let hue = 0, s = 0, l = (mx + mn) / 2;
  if (mx !== mn) { const d = mx - mn; s = l > 0.5 ? d / (2 - mx - mn) : d / (mx + mn); if (mx === r) hue = (g - b) / d + (g < b ? 6 : 0); else if (mx === g) hue = (b - r) / d + 2; else hue = (r - g) / d + 4; hue /= 6; }
  return `${Math.round(hue * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
}
// Maps @dashfi/svelte shadcn role -> our tailwind source role (only the ones that derive from our tokens).
const libMap = { background: 'background', foreground: 'foreground', card: 'card', 'card-foreground': 'card-foreground', popover: 'popover', 'popover-foreground': 'popover-foreground', primary: 'primary', 'primary-foreground': 'primary-foreground', secondary: 'secondary', 'secondary-foreground': 'secondary-foreground', muted: 'muted', 'muted-foreground': 'muted-foreground', accent: 'accent', 'accent-foreground': 'accent-foreground', destructive: 'destructive', 'destructive-foreground': 'destructive-foreground', brand: 'brand', 'brand-foreground': 'brand-foreground', cobalt: 'cobalt', 'cobalt-foreground': 'cobalt-foreground', border: 'border', input: 'input', ring: 'ring' };
const twByName = Object.fromEntries(tw.map((t) => [t.name, t.value]));
const libLine = (role, mode) => `\t\t--${role}: ${hexToHsl(resolve(mode === 'light' ? lightOf(twByName[libMap[role]]) : darkOf(twByName[libMap[role]])))};`;
const libRoles = Object.keys(libMap);
const libCss = `/* GENERATED reference (HSL) for @dashfi/svelte's global.css token block — from tokens/dashbook.tokens.json.
   Covers the roles that derive from Dashbook tokens. The lib ALSO defines success/warning/sidebar-*/
   card-surface-* (not sourced here yet) and uses primary=ink / destructive=orange (already matched here).
   This is a REFERENCE for the packages/brand migration — wiring the lib to consume it is a reviewed core change. */
@layer base {
\t:root {
${libRoles.map((r) => libLine(r, 'light')).join('\n')}
\t}
\t.dark {
${libRoles.map((r) => libLine(r, 'dark')).join('\n')}
\t}
}
`;

mkdirSync(join(root, 'src/lib/generated'), { recursive: true });
writeFileSync(join(root, 'src/lib/generated/tokens.css'), tokensCss);
writeFileSync(join(root, 'src/lib/generated/theme.css'), themeCss);
writeFileSync(join(root, 'src/lib/generated/tokens.ts'), tokensTs);
writeFileSync(join(root, 'tokens/figma.tokens.json'), JSON.stringify(figma, null, 2) + '\n');
writeFileSync(join(root, 'tokens/figma-apply.gen.js'), figmaApply);
writeFileSync(join(root, 'tokens/figma-text-styles.gen.js'), figmaText);
writeFileSync(join(root, 'tokens/lib-tokens.reference.css'), libCss);

console.log(`tokens built: ${base.length} base, ${product.length} product, ${mAlias.length} mkt-alias, ${marketing.length} mkt-role, ${scale.length} scale, ${tw.length} tailwind, ${typo.length} text styles`);
console.log('  css: tokens.css, theme.css | ts: tokens.ts | figma: figma.tokens.json, figma-apply.gen.js, figma-text-styles.gen.js | lib: lib-tokens.reference.css');
